### ISSUE TITLE
Fix race issues in test

### ISSUE THREAD

**Issue by skaldesh** [desertbit/orbit#14]
I am not exactly sure yet why, but the go test -race command fails due to some issues in the test files. It seems like it is the global controls that are being shared and also written to, though in a thread safe manner, but not for the go race detector, as we simply register unique functions per test func. 

Fix this with a unique pair of controls for each test. This should also fix the code coverage being n/a

**Comment by r0l1** [comment]
Too old. Moving to new version soon.
