### ISSUE TITLE
Include version field in orbit file

### ISSUE THREAD

**Issue by r0l1** [desertbit/orbit#22]
Include a version field set to 1 in the orbit file.. This field is mandatory.

```
version 1
```

**Comment by skaldesh** [comment]
@r0l1 What to do with the version? I guess it should be part of the session handshake?

**Comment by skaldesh** [comment]
In addition, also implement #23 :  
Include an internal version of the code gen into the generated code. Force update the file, even if the cache tells not to. This forces rebuilds with newer code gen implementations.
