### ISSUE TITLE
Send Stream arg/ret only once

### ISSUE THREAD

**Issue by skaldesh** [desertbit/orbit#37]
Sometimes it would be cool to open a stream, send one argument for example once to the peer, and then just stream some data back. Other way round also possible.  

Maybe we can support something like this:
```
stream test {
    once arg: {
        id string
    }
    ret: {
        data string
    }
}
```
I would not change the way orbit works under the hood. Rather this be solved within the codegen, where the testArgChan is not exposed to the user, but used once internally and the argument is taken as standard method parameter:
```go
retChan, err := api.Test("myID")
```

**Comment by r0l1** [comment]
```
stream test {
    init arg: {
        id string
    }
    ret: {
        data string
    }
}
```

**Comment by skaldesh** [comment]
Too much magic, the other way round is also difficult from an API perspective. It would have to be a stream that accepts arguments and then magically returns some struct?  
I guess it makes only sense for the use case outlined in my first post, and for that it is not really that useful overall
