### ISSUE TITLE
Add Go Tags support for orbit types

### ISSUE THREAD

**Issue by gosticks** [desertbit/orbit#43]
It would be great to set custom Go Tags on Orbit types. 
My suggestion is to keep the syntax close to the one found in golang.
```
type MyType {
     string name `example:"name"`
}
```

**Comment by skaldesh** [comment]
Yes, generally we want to support this.  
Syntax is then just plain go struct tag syntax. The current validator tags would have to be written like this: \`validator:"required"\`.

**Comment by skaldesh** [comment]
One problem I see is, that the current `.orbit` syntax allows to do the following:  
```
arg: int 'min=5'
```
How should this be translated to the new syntax? It made sense back then, since it would only contain validation tags...

**Comment by skaldesh** [comment]
After discussing with @r0l1 (see [here](https://github.com/desertbit/orbit/issues/44#issuecomment-624576883)), we decided to drop support of single values and just allow structs from now on. THerefore, the aforementioned problem is no longer relevant
