### ISSUE TITLE
time.Duration not supported with tinylib/msgp codegen

### ISSUE THREAD

**Issue by skaldesh** [desertbit/orbit#50]
as the title says  

We have the option to fork the repo and implement it ourselves, or to open an issue there and ask, if they would include it (there has not been much activity lately, so might take a while)

**Comment by r0l1** [comment]
Seams, we have to add an extension: https://github.com/tinylib/msgp/wiki/Using-Extensions
We could suggest a pull request.

**Comment by skaldesh** [comment]
I discovered today the `shim` directive: https://github.com/tinylib/msgp/wiki/Preprocessor-Directives  

```go
//msgp:shim time.Duration as:int64 using:encode/decode
package controller

import "time"

func encode(d time.Duration) int64 {
	return int64(d)
}

func decode(i int64) time.Duration {
	return time.Duration(i)
}
```
