### ISSUE TITLE
State which errors can be returned by calls/streams

### ISSUE THREAD

**Issue by skaldesh** [desertbit/orbit#67]
Right now, every call/stream can return every error that one defines in the .orbit file.  
How about defining explicitly which call/stream can return which error?  

This would have two benefits:
1. The user knows exactly which errors to check for when handling errors
2. A slight performance benefit, as in the generated code, not all errors need to be checked with `errors.Is()` and `switch err.Code()`

**Comment by skaldesh** [comment]
Suggestions on how it could look in the `.orbit` file:  
```
errors {
    thisIsATest = 1
    iAmAnError = 2
    // ...
}
service {
    call sayHi {
        arg: {
            name string `validate:"required,min=1"`
            ts time
        }
        ret: {
            res []int `validate:"required,min=1"`
        }
        errors: [1, 2] // 1
        errors: 1, 2 // 2
        errors: [thisIsATest, iAmAnError] // 3
        errors: thisIsATest, iAmAnError // 4
    }
}
```
Off of the top of my head, I suggest these 4 options. I like 1 and 2, while 3 and 4 feel too verbose.

**Comment by r0l1** [comment]
Good idea. We should also include the possible errors into the function documentation (codegen).

>  I suggest these 4 options.

I would rather go with 4. If the orbit file is long, then scrolling to the definition might be required. And if one value changes, one must adjust all occurrences.

**Comment by skaldesh** [comment]
>  If the orbit file is long, then scrolling to the definition might be required.

Agreed

> And if one value changes, one must adjust all occurrences.

Isn't it more likely that you change the name of an error instead of its id?

**Comment by r0l1** [comment]
> Isn't it more likely that you change the name of an error instead of its id?

Search and replace is easier on a string as on a number. I would see it as a typical enum, which expresses the meaning to the programmer. `errors: 1, 2` is quite non-descriptive. It's shorter, but feels wrong.

**Comment by skaldesh** [comment]
Agreed, good points!  

So lets implement it like this:  
```
errors {
    thisIsATest = 1
    iAmAnError = 2
    // ...
}
service {
    call sayHi {
        arg: {
            name string `validate:"required,min=1"`
            ts time
        }
        ret: {
            res []int `validate:"required,min=1"`
        }
        errors: thisIsATest, iAmAnError
    }
}
```

One thing we must decide:  
What to do, when the dev forgets to add the `errors` declaration to a call/stream? We could either not check for errors then (breaking change) or we default to checking all errors, like we do now (backwards compatible change)

**Comment by r0l1** [comment]
Sounds good.

> What to do, when the dev forgets to add the errors declaration to a call/stream? We could either not check for errors then (breaking change) or we default to checking all errors, like we do now (backwards compatible change)

Let's check for all errors, if not specified.

**Comment by skaldesh** [comment]
I just implemented it and its looking good.
One thing I noticed: In the sample/full `.orbit` file, I wanted to give every call/stream now their specific errors.  
Sometimes, I know that a call can not return any predefined error. So I would like to state, that no errors must be checked. With the current syntax, it is not obvious how to do this:  

Example:
```
call getUsers {
    arg: {
        afterUserID string
        count int `validate:"min=1,max=100"`
    }
    ret: { users []UserOverview }
    // errors: "" ?
}
```
With `errors: [err1, err2]` it would be easy: `errors: []`  
@r0l1 what do you think?

**Comment by skaldesh** [comment]
Or maybe default behaviour must be, that no errors are checked after all...

**Comment by skaldesh** [comment]
I just realized we probably do simply not need to check for errors, if no `errors:` block is present.  
If a user wants to check for an error, he simply must state that the call/stream can return it...
